# Generated by Django 6.0.7 on 2026-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='formato',
            field=models.CharField(choices=[('pieza', 'Pieza Individual'), ('lote', 'Caja / Lote')], default='pieza', max_length=10, verbose_name='Formato de venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='piezas_por_caja',
            field=models.PositiveIntegerField(default=1, help_text='Si es por lote, especifica cuántas piezas individuales contiene.', verbose_name='Piezas por Caja/Lote'),
        ),
    ]
